dist: bionic
os: linux
language: python

services:
  - docker

python:
  - 3.8

env:
  - ESALE_SERVER_BACKEND: 172.17.0.1:8000

before_install:
  - docker run -d -p 1025:1025 -p 8025:8025 mailhog/mailhog
  - docker ps -a

install:
  - make install
  - make mk-migrations APP=accounts
  - make migrate
  - make mk-migrations
  - make migrate
  - make create-superuser
  - make serve-test &
  - until curl -s $ESALE_SERVER_BACKEND; do sleep 5; done

script:
  - make test

cache:
  - pip
