# Generated by Django 3.0.4 on 2020-04-10 08:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 10, 3, 9, 4, 74125, tzinfo=utc), verbose_name='Registered Date'),
        ),
    ]
