# Generated by Django 3.0.4 on 2020-04-10 13:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 10, 8, 1, 57, 398013, tzinfo=utc), verbose_name='Date of Registration'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 10, 8, 1, 57, 398013, tzinfo=utc), verbose_name='Registered Date'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='NP'),
        ),
    ]
