# Generated by Django 3.0.4 on 2020-04-10 14:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200410_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('l_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='NP')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, unique=True, verbose_name='Email Address')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2020, 4, 10, 8, 22, 9, 876987, tzinfo=utc), verbose_name='Date of Registration')),
                ('tot_due', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('tot_received', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('image', models.ImageField(default='default.jpg', upload_to='vendor', verbose_name='Image(Vendor)')),
            ],
            options={
                'verbose_name_plural': 'Vendors',
            },
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 10, 8, 22, 9, 876987, tzinfo=utc), verbose_name='Date of Registration'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 10, 8, 22, 9, 876987, tzinfo=utc), verbose_name='Registered Date'),
        ),
    ]
