# Generated by Django 3.0.4 on 2020-04-10 10:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200410_0854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('l_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.IntegerField(unique=True, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, unique=True, verbose_name='Email Address')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2020, 4, 10, 5, 2, 25, 201275, tzinfo=utc), verbose_name='Date of Registration')),
                ('tot_due', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('tot_received', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('image', models.ImageField(default='default.jpg', upload_to='customer', verbose_name='Image(Customer)')),
            ],
            options={
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 10, 5, 2, 25, 201275, tzinfo=utc), verbose_name='Registered Date'),
        ),
    ]
