# Generated by Django 3.0.4 on 2020-04-10 13:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200410_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 10, 7, 15, 58, 254201, tzinfo=utc), verbose_name='Date of Registration'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 10, 7, 15, 58, 254201, tzinfo=utc), verbose_name='Registered Date'),
        ),
    ]
